@startuml

package xpress
{
    package osal{
        class thread<user_impliment_class,osal_target_class=default_target>{
            -m_user_obj:user_impliment_class,
            -m_target_obj:osal_target_class,
            -{static}*main(void*):void,
            +thread(),
            +~thread(),
            +priority(uint32_t):int32_t,
            +priority(void):uint32_t,
            +stack_size(uint64_t):int32_t,
            +stack_size(void):uint64_t,
            +create(void):int32_t,
            +destroy(void):int32_t,
            +is_running(void):int32_t,
            +join(void):int32_t,
        }
    }
}

@enduml

